import { spawn } from "child_process";
import { mkdir } from "fs/promises";
import fs from "fs";

import { db } from "../db";
import { Deployment } from "../db/schema";
import { desc, eq, sql } from "drizzle-orm";
import { EventEmitter } from "events";


export const logEmitter = new EventEmitter();

export async function startDeployment(id: string, gitUrl: string) {
    const imageTag = `deploy-${id}`;
    const workingDir = `/tmp/${id}`;

    try {
        await mkdir(workingDir, { recursive: true });

        await db.update(Deployment)
            .set({ status: "cloning", imageTag })
            .where(eq(Deployment.id, id));

        const clone = spawn("git", ["clone", gitUrl, "."], { cwd: workingDir });

        clone.stderr.on("data", (data) => appendLogs(id, data.toString()));

        clone.on("close", async (code) => {
            if (code !== 0) {
                await markFailed(id, "Git clone failed.", workingDir);
                return;
            }

          
            const hasManifest = fs.existsSync(`${workingDir}/package.json`) || 
                               fs.existsSync(`${workingDir}/go.mod`) || 
                               fs.existsSync(`${workingDir}/requirements.txt`);

            if (!hasManifest) {
                console.log("No manifest found. Injecting static server...");
                appendLogs(id, "\n[Brimble] No manifest detected. Configuring as a static site...");
                
                const staticPkg = {
                    name: "static-deployment",
                    description: "Auto-generated by Brimble Engine",
                    dependencies: { "serve": "latest" },
                    scripts: { "start": "serve -s . -l 3000" }
                };
                
                fs.writeFileSync(`${workingDir}/package.json`, JSON.stringify(staticPkg, null, 2));
            }
            // ----------------------------------------

            console.log(`Starting build for ${id}...`);
            runBuild(id, imageTag, workingDir);
        });
    } catch (err) {
        const error = err as Error;
        await markFailed(id, `Initialization failed: ${error.message}`, workingDir);
    }
}

async function runBuild(id: string, imageTag: string, workingDir: string) {
    await db.update(Deployment)
        .set({ status: "building" })
        .where(eq(Deployment.id, id));

    const railpackPath = "/usr/local/bin/railpack";

    const build = spawn(railpackPath, ["build", ".", "--name", imageTag,], {
        cwd: workingDir,
        env: { ...process.env, DOCKER_HOST: "unix:///var/run/docker.sock", BUILDKIT_HOST: "docker-container://buildkit" }
    });

    build.stdout.on("data", (data) => appendLogs(id, data.toString()));
    build.stderr.on("data", (data) => {
        const log = data.toString();
        console.error(`[Railpack Error]: ${log}`);
        appendLogs(id, log);
    });

    build.on("close", async (code) => {
        if (code !== 0) {
            await markFailed(id, "Railpack build failed", workingDir);
            return;
        }
        await deployContainer(id, imageTag);
    });
}


async function deployContainer(id: string, imageTag: string) {
    try {
        await db.update(Deployment)
            .set({ status: "deploying" })
            .where(eq(Deployment.id, id));

       
        const lastDeployment = await db.select().from(Deployment).orderBy(desc(Deployment.port)).limit(1);
        const nextPort = lastDeployment[0]?.port ? lastDeployment[0].port + 1 : 4000;

      
        const dockerRun = spawn("docker", [
            "run", "-d",
            "-p", `${nextPort}:80`,
            "--name", imageTag,
            imageTag
        ]);

        let containerId = "";
        dockerRun.stdout.on("data", (data) => {
            containerId += data.toString().trim();
        });

        dockerRun.on("close", async (code) => {
            if (code !== 0) {
                await markFailed(id, "Docker run failed. Check if port is already in use.", `/tmp/${id}`);
                return;
            }

            const liveUrl = await updateCaddyConfig(id, nextPort);

            await db.update(Deployment)
                .set({
                    status: "running",
                    containerId: containerId,
                    port: nextPort,
                    liveUrl: liveUrl,
                    logs: sql`${Deployment.logs} || ${` \n ✅ Deployment live at ${liveUrl}`}`
                })
                .where(eq(Deployment.id, id));

            console.log(`Deployment ${id} is live at ${liveUrl}`);
        });

    } catch (error) {
        const err = error as Error;
        await markFailed(id, err.message, `/tmp/${id}`);
    }
}



async function appendLogs(id: string, newLog: string) {
    logEmitter.emit(id, newLog);
    await db.update(Deployment)
        .set({ logs: sql`${Deployment.logs} || ${newLog}` })
        .where(eq(Deployment.id, id));
}

async function markFailed(id: string, reason: string, workingDir: string) {
    console.error(`Deployment ${id} failed: ${reason}`);

    await db.update(Deployment)
        .set({
            status: "failed",
            logs: sql`${Deployment.logs} || ${` \n ERROR: ${reason}`}`
        })
        .where(eq(Deployment.id, id));

    fs.rmSync(workingDir, { recursive: true, force: true });

}


async function updateCaddyConfig(id: string, port: number) {
  const domain = `${id}.localhost`;
  
  const routePayload = {
    match: [{ host: [domain] }],
    handle: [{
      handler: "reverse_proxy",
      upstreams: [{ dial: `localhost:${port}` }]
    }],
    terminal: true
};


  try {
    const response = await fetch(`${process.env.CADDY_ENDPOINT!}`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(routePayload),
    });

    if (!response.ok) throw new Error("Caddy API refused the route");

    return `http://${domain}`;
  } catch (error) {
    console.error("Caddy Logic Error:", error);
    return `http://localhost:${port}`;
  }
}

//caddy run --config Caddyfile
//sudo caddy reload --config Caddyfile